### PR TITLE
Prettier 2

### LINKED ISSUE #137: Add Solidity config file to standardize code format
add prettier linter for solidity

### PR DESCRIPTION
**Pull request by daopunk**
scripts:
    "prettier-proxy": "prettier --write --plugin=prettier-plugin-solidity 'src/contracts/proxies/*.sol'",
    "prettier-deployment": "prettier --write --plugin=prettier-plugin-solidity 'script/GoerliContracts.s.sol'"

after we run a deployment, we can run `prettier-deployment` to target the GoerliContracts file

closes #137

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Please also run on Vault721

Also, does this run automatically when you save a file in your editor (vscode)?

**Comment by daopunk** [comment]
i ran this on the Proxies folder (without Proxy Actions), which runs on Vault721, but since i wrote that in my editor, there are no prettier updates (which means the code since i began working, and originally asked the formatting question, has been formatted to my editor)

doesn't run auto. i can do that tho. on `push` or when?

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- Run lint:fix
- Open a new branch for hai/main. If there are mamny changes, try using the commit from our last merge
- Make a PR against this one to compare linting changes 
- Figure out how to get editors to run solhint on save for the specific file

**Comment by daopunk** [comment]
i pulled from upstream after running linter and there were no changes

**Pull request merged**
