### PR TITLE
[blocked] add .prettier file, added scripts to package.json, ran prettier script

### LINKED ISSUE #137: Add Solidity config file to standardize code format
add prettier linter for solidity

### PR DESCRIPTION
**Pull request by daopunk**
closes #137 

changes
- .prettierrc file
- scripts in package.json

ran prettier script on all .sol files

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Before merging this lets compare branches with hai. If the audit is based on line changes, then this would have a huge impact on the git diff.

**Comment by pi0neerpat** [comment]
Options:

1. Run prettier only on our modified files: ODProxy, Vault721, VaultManager
2. Run everything, but only give the 3 modified files to Auditors
3. Modify formatter config to the current formatting
4. Similar to 1, run on our changes, then later run on everything

TODO:

- Verify what formatter hai is using (Hunter)
- document when we diverged from HAI (Patrick)

Decision:

- We decided on option 4

**Comment by daopunk** [comment]
i made it new pull request. can we close this one?

**Comment by pi0neerpat** [comment]
Replaced by #151

**Pull request closed without merging**
