### PR TITLE
Closed #323 relayer decimal scaling

### LINKED ISSUE #323: Safe manager upgrade plan
We have decided to not implement any code changes for issue #232. Rather, we will devise a plan for how to perform a safe manager upgrade and avoid the original issue raised in the code audit. I believe this is sufficient to address the audit finding. 

Please write a comprehensive set of instructions for our team and the dao on how to upgrade the safe manager, per Joseph's high-level outline here:

> 1. create a new safemanager that can only be started by the DAO
> 2. the DAO votes to update the address for the ODSafeManager and start the new one
> 3. as part of calling the start function on the new ODSafeManager it copies over all the data it needs, and some of it can already be pre-written into it
> 4. the old ODSafeManager still exists but is no longer connected to anything nor has any special permissions

The key elements of the above plan are that:
- Data integrity is maintained throughout the upgrade without needing to "pause" the protocol. Eg. ownership cannot be lost or manipulated during the upgrade
- The governance process may take multiple days between when contracts are deployed, and when proposal is executed. Again, data integrity should be maintained. The suggestion is to copy the data in the same moment as the safe manager is changed. This may require additional contract(s). 

You're welcome to organize it however you see fit, but here is my suggested format:

## Overview

_Explain the high level process, so the average defi user can understand_

## Code Audit fix

_How this addresses the potential issues raised in "#381 updating address Vault721.safeManager breaks NFV minting"_

## Operational Steps

_A clear and concise set of procedures, expanding on Joseph's outline. Please include code snippets, psuedo-code, and recommendations for additional research in any areas you are unsure of._ 

## Risks and Security

_Discuss security concerns, potential pitfalls to be aware of, and any additional security risks associated with the process_

### PR DESCRIPTION
**Pull request by St4rgarden**
Implemented the simple fix for #233  to the exact specification you provided @pi0neerpat.  I double checked your implementation from the issue and I have previously used and tested that exact same implementation.

The one thing I added is this abs function for returning the absolute value of a negative signed integer:

```
// @notice Return the absolute value of a signed integer as an unsigned integer
  function abs(int256 x) internal pure returns (uint256) {
    x >= 0 ? x : -x;
    return uint256(x);
  }
  ```

### CODE REVIEW

**Comment by daopunk** [comment]
Due to Solidity versioning issues, i created a new repo for the relayers. so can you actually submit a PR on the new repo linked the same issue: https://github.com/open-dollar/od-relayer/tree/dev/src

Currently working on migrating relayer tests to new repo.

**Comment by pi0neerpat** [comment]
Please open this PR in the new relayer repo

**Comment by St4rgarden** [comment]
> Due to Solidity versioning issues, i created a new repo for the relayers. so can you actually submit a PR on the new repo linked the same issue: https://github.com/open-dollar/od-relayer/tree/dev/src
> 
> Currently working on migrating relayer tests to new repo.

It doesn't look like I am able to link to the same issue - as the issue isn't included in the new repo.

**Comment by St4rgarden** [comment]
Deleted branch; new code and pr is in [od-relayer](https://github.com/open-dollar/od-relayer/pull/8)

**Pull request closed without merging**
