### PR TITLE
Fix  some inconsistence

### PR DESCRIPTION
**Pull request by ngmachado**
This PR removes returns values when using solidity named return variables. This will fix the coverage %.

### CODE REVIEW

**Comment by ngmachado** [comment]
This PR was extended to bump more coverage %

Our contract folder state now:

Screenshot 2024-01-21 at 11 54 58

Global:

Screenshot 2024-01-21 at 11 55 16

**Review by pi0neerpat — COMMENTED** [review]
Assigning review to @daopunk

**Review by daopunk — APPROVED** [review]
awesome!

**Review by pi0neerpat — APPROVED** [review]

**Comment by daopunk** [comment]
@ngmachado i'm merging since i'm about to run a new deployment, but will let you delete the branch when you are ready

**Pull request merged**
