### PR TITLE
287 create surplus + debt in anvil

### LINKED ISSUE #287: Create Surplus + Debt in Anvil
The frontend/backend team needs a script to efficiently create surplus and debt when running the local Anvil blockchain.

Goal:
- 3 scripts
- each script creates conditions for a specific type of auction
- instructions for running script for FE team

The FE team should be able to start an instance of Anvil, run these scripts independently to bring the state of the protocol to an auction, so the FE team can tests auctions on the app (UI) efficiently and locally

### PR DESCRIPTION
**Pull request by St4rgarden**
Closes #287 

There's two new scripts in the `script/states` folder.  Each one has a commented CLI command which can run the script following an Anvil instantiation and deployment.

They're both quite simple but required a number of changes to `AnvilFork.t.sol` in order to get everything working.  Namely we were getting compiler failures from mistaken state variable names, none of the tokens were labelled, and the oracles were not pulled or instantiated into the AnvilFork file.  I also updated the `setUp` function of AnvilFork to provide some bare minimum basic SAFE state.

The scripts themselves are pretty self-explanatory:

DebtState enables us to degrade the health of all user's SAFE positions by manipulating the denominated asset price (wstETH).  Since all of the collateral types are denominated in this asset price - setting the price to nearly zero makes all the positions ready for liquidation; which could then be followed by a bad debt auction.  Then of course we have to update each individual denominated oracle and finally the oracle relayer as well:

```  function setPriceLowToTriggerDebtScenario() public {

    vm.prank(J);
    // change the wstETH delayed oracle price very low
    testOracles[0].setPriceAndValidity(1, true);

    // update all the denominatedOracles
    for (uint256 i = 0; i < denominatedOracles.length; i++) {
      denominatedOracles[i].getResultWithValidity();
    }

    for (uint256 i = 0; i < cTypes.length; i++) {
      // call updateCollateralPrice on the oracle relayer
      oracleRelayer.updateCollateralPrice(cTypes[i]);
    }

  }

  function run() public {
    setUp();
    setPriceLowToTriggerDebtScenario();
  }```
  
  SurplusState is incredibly simple.  We just open a bunch of user safes; warp the time forward a year and collect the tax on all collateral types and then check to make sure that the accounting engine has plenty of surplus:
  
  ```  function run() public {
    setUp();
    vm.warp(block.timestamp + 365 days);
    taxCollector.taxMany(0, 3);
    uint256 coinBalance = safeEngine.coinBalance(address(accountingEngine));
    uint256 debtBalance = safeEngine.debtBalance(address(accountingEngine));

    console.log("Coin Balance of Accounting Engine");
    console.logUint(coinBalance);
    console.log("Debt Balance of Accounting Engine");
    console.logUint(debtBalance);
  }```

### CODE REVIEW

**Comment by daopunk** [comment]
@pi0neerpat this was marked as draft until scripts to fully complete auctions are added. currently, scripts bring protocol to where an auction can be initiated

**Comment by St4rgarden** [comment]
Okay so here's the new instructions:

There are 5 new scripts in script/states folder.  Each script in the states folder has a commented forge command at the bottom that can launch the script.  They can be used in following ways after a local anvil deployment immediately after following the instructions commented in the top of the `AnvilFork.t.sol` file :

- `DebtState.s.sol` puts every SAFE in jeopardy of liquidation by driving the non-wstETH collateral prices down.  After running DebtState any SAFEs can be liquidated freely for testing.
 
- `LiquidationAuction.s.sol` takes DebtState a step further and liquidates every SAFE on the platform.  It then initiates and completes a single collateral auction.  We also create a chunk of unbacked debt in the accounting engine which enables launching a debt auction.  This state can be used to test liquidations, launching collateral auctions, launching a debt auction or viewing a completed collateral auction.

- `DebtAuction.s.sol` takes LiquidationAuction a step further and creates a large amount of unbacked debt in the AccountingEngine; which allows us to then create a debt auction.  The debt auction is then bid on and settled.  This allows testing of viewing a completed debt auction.

- SurplusState.s.sol pushes the clock forward so that the protocol accrues surplus.  It can be used to test launching a SurplusAuction.

- SurplusAuction.s.sol takes SurplusState a step farther, and initiates a surplus auction, bids on it and settles it.  It can be used to test viewing a completed surplus auction.

**Review by daopunk — APPROVED** [review]
approved @pi0neerpat

**Review by pi0neerpat — APPROVED** [review]
Excellent thank you!

**Pull request merged**
